require('dotenv').config();
console.log(
  process.env.DATABASE_HOST,
  process.env.DATABASE_USERNAME,
  process.env.DATABASE_PASSWORD,
  process.env.DATABASE_PORT,
  process.env.DATABASE_NAME,
  process.env.ACCESS_SECRET,
  process.env.NODE_ENV,
  process.env.HTTPS_PORT
);
