require('dotenv').config();
console.log(
  process.DATABASE_HOST,
  process.DATABASE_USERNAME,
  process.DATABASE_PASSWORD,
  process.DATABASE_PORT,
  process.DATABASE_NAME,
  process.ACCESS_SECRET,
  process.NODE_ENV,
  process.HTTPS_PORT
);
